enable-magisk-update = false
patches-version = "v2.227.0-dev.22"
integrations-version = "v0.154.0-dev.7"
cli-source = "j-hc/revanced-cli"

[YouTube]
cli-source = "j-hc/revanced-cli"
build-mode = "apk"
included-patches = "'Enable song search' 'MaterialYou' 'Theme' 'Custom branding name YouTube'"
excluded-patches = "'Custom package name' 'Return YouTube Dislike' 'Custom branding heading' 'Custom branding icon YouTube' 'Alternative thumbnails'"
version = "19.23.40"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
arch = "arm64-v8a"
apkmirror-arch = "arm64-v8a"


[Music]
cli-source = "j-hc/revanced-cli"
# enabled = false
build-mode = "apk"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
apkmirror-arch = "arm64-v8a"
included-patches = "'Custom branding icon for YouTube Music' 'Custom branding name for YouTube Music' 'Hide overlay filter' 'Hide player overlay filter'"
excluded-patches = "'Enable debug logging'"
